export const LOGIN_COPY = {
  TITLE: 'Log in to TrackIt',
  DESCRIPTION: 'Enter your email and password to access your dashboard',
  PENDING_APPROVAL_TITLE: 'Organization Pending Approval',
  LOGIN_FAILED_TITLE: 'Login Failed',
  GENERIC_ERROR: 'An error occurred while logging in. Please try again.',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'admin@example.com',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: '••••••••',
  SUBMIT_BUTTON_PENDING: 'Logging in...',
  SUBMIT_BUTTON: 'Log In',
  FOOTER_PROMPT: "Don't have an account?",
  FOOTER_LINK: 'Register your organization',
} as const;

export const REGISTER_COPY = {
  TITLE: 'Register Organization',
  DESCRIPTION: 'Create a new tenant organization and initial administrator account',
  REGISTRATION_FAILED_TITLE: 'Registration Failed',
  GENERIC_ERROR: 'Registration failed. Please check your information and try again.',
  ORG_NAME_LABEL: 'Organization Name',
  ORG_NAME_PLACEHOLDER: 'Apex Auto Repair',
  ADMIN_NAME_LABEL: 'Admin Full Name',
  ADMIN_NAME_PLACEHOLDER: 'Jane Doe',
  ADMIN_EMAIL_LABEL: 'Admin Email',
  ADMIN_EMAIL_PLACEHOLDER: 'admin@apexauto.com',
  ADMIN_PASSWORD_LABEL: 'Password',
  ADMIN_PASSWORD_PLACEHOLDER: '••••••••',
  CONFIRM_PASSWORD_LABEL: 'Confirm Password',
  CONFIRM_PASSWORD_PLACEHOLDER: '••••••••',
  SUBMIT_BUTTON_PENDING: 'Registering...',
  SUBMIT_BUTTON: 'Register Organization',
  FOOTER_PROMPT: 'Already have an account?',
  FOOTER_LINK: 'Log in',
  SUCCESS_TITLE: 'Registration Submitted',
  SUCCESS_DEFAULT_ORG: 'Your organization',
  SUCCESS_DESCRIPTION_SUFFIX: 'has been successfully registered.',
  SUCCESS_ALERT_TITLE: 'Pending Approval / Ready to Sign In',
  SUCCESS_ALERT_DESCRIPTION:
    'If your platform requires admin approval, your account will be activated once approved by a superadmin. Otherwise, you can log in right away.',
  PROCEED_TO_LOGIN_BUTTON: 'Proceed to Login',
  BACK_TO_LOGIN_LINK: 'Back to Login',
} as const;
